; Description de la configuration (commentaire)
; Exemple de configuration locale
; Chaîne de connexion PDO (hôte, base, encodage)
; Nom d'utilisateur de la base de données

DB_NAME = "mejiwoo"
DB_HOST = "127.0.0.1"
DB_USERNAME = "test"
DB_PASSWORD = "test"
